### ISSUE TITLE
optparse-generic bump needed

### ISSUE THREAD

**Issue by ilovezfs** [Gabriel439/Haskell-Dhall-JSON-Library#6]
http://hackage.haskell.org/package/optparse-generic-1.1.5/optparse-generic.cabal
requires `time                 >= 1.5     && < 1.7`

http://hackage.haskell.org/package/optparse-generic/optparse-generic.cabal
requires `time                 >= 1.5     && < 1.9`

GHC 8.2.1 ships with `time-1.8.0.2`.

**Comment by ilovezfs** [comment]
Thanks again!

**Comment by Gabriel439** [comment]
You're welcome! :)

**Comment by ilovezfs** [comment]
@Gabriel439 voilà https://github.com/Homebrew/homebrew-core/pull/16765
